# Set build language to Node JS
language:               node_js

# Set the version of Node JS to use
node_js:                lts/*

env:
    # Ensure HTTPS is used
    - NODE_TLS_REJECT_UNAUTHORIZED=1

cache:
    # Ensure packages cached via yarn are cached
    yarn:               true
    directories:
        # Ensure npm packages are cached
        - node_modules

before_install:
    # Configure access token to enable pushing to the repository
    - git remote set-url origin https://elemental9:${github_token}@github.com/elemental9/elemental9.github.io.git

    # Set commit username
    - git config --global user.name "ROS Bot"

    # Set commit email
    - git config --global user.email "richiebendall@gmail.com"

    # Navigate to the source directory
    - cd src

    # Install the yarn package manager
    - npm install -g yarn

install:
    # Install required packages
    - yarn install --non-interactive workbox-cli sitemap-generator-cli

script:
    # Generate the service worker
    - npx workbox injectManifest workbox-config.js

    # Generate Sitemap
    - npx sitemap-generator-cli https://www.elemental9.ml

    # Minify the HTML code
    - npx html-minifier --input-dir . --output-dir . --collapse-boolean-attributes --collapse-inline-tag-whitespace --conservative-collapse --decode-entities --minify-css --minify-js --minify-urls --preserve-line-breaks --remove-attribute-quotes --remove-comments --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --use-short-doctype --minify-css true --minify-js true --file-ext html

deploy:
    provider:           pages
    local_dir:          .
    github_commit:      "CI | Built the website [skip ci]"
    skip_cleanup:       true
    github_token:       $github_token
    fqdn:               www.elemental9.ml
    committer_from_gh:  true

after_deploy:
   # Clear CloudFlare cache
   - |
     curl --request DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
      --header "X-Auth-Email: richiebendall@gmail.com" \
      --header "X-Auth-Key: ${cf_api_key}" \
      --header "Content-Type: application/json" \
      --data '{"purge_everything":true}'

   # Recrawl site for Google Search
   - curl -s https://www.google.com/ping?sitemap=https://www.elemental9.ml/sitemap.xml > /dev/null && echo Google Search recrawl requested.

notifications:
   # Disable emails for build status notifications
   email:              false
